# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EYRckmyqmRjj5d_2kFZ5WLtKIgWBFTeM
"""

#trying to use some random curse words found online
tweets = ["he is pridefull pig","she is a bitch"]
slurs = ["bitch","pridefull pig"]

def get_slur_score(tweet,slurs):
  words = tweet.split()
  slur_count = 0
  #assuming that the slur words are lowerd for convinience
  for i in range(1,len(words)):

      if(words[i-1].lower() in slurs):
        slur_count+=1
      #assuming that the maximum slur word combinations are of two words
      if(words[i-1].lower()+ " "+words[i].lower() in slurs):
        slur_count+=1
  if(words[-1].lower() in slurs):
    slur_count+=1
  return slur_count/len(words)

get_slur_score(tweets[1],slurs)



